name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      hello:
        image: hello-world
    
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
